### PR TITLE
Clojure ci - lein

### PR DESCRIPTION
**Pull request by antonioalonzi**
I think the biggest problem is that the project has not been created with [lein](https://leiningen.org/).

### CODE REVIEW

**Comment by allentiak** [comment]
Not using Leiningen was on purpose :-)
That being said, once the `clojure -Sdescribe` command works, the rest can be fixed...

**Comment by antonioalonzi** [comment]
The nice thing of `lein` is that it can automate you build process with zero code and that you can deploy to heroku with one liner:
 - `web: lein run -m demo.web $PORT`

(see https://devcenter.heroku.com/articles/procfile)

**Comment by allentiak** [comment]
@antonioalonzi 
I know about the existence of Lein, Boot and Clojure CLI :-)
All of them are build tools for Clojure.

When I first started with Clojure, I deliberately chose to skip Lein altogether, and so I learned Boot. Lately, however, I have moved to Clojure CLI.

To (somehow) quote @seancorfield, the leaner, the better :-)

**Comment by allentiak** [comment]
But thanks for mentioning this anyways :-)

**Comment by seancorfield** [comment]
Since I was mentioned...

Here's how my `next.jdbc` project runs on Circle CI: https://github.com/seancorfield/next-jdbc/blob/master/.circleci/config.yml -- `next.jdbc` is a `deps.edn` project.

And it also runs CI via GitHub Actions: https://github.com/seancorfield/next-jdbc/blob/master/.github/workflows/test.yml

**Comment by allentiak** [comment]
Thanks, @seancorfield !

I was considering using that code, but somehow I forgot about it...
Thanks for the pointer! :-)

**Pull request closed without merging**
